Repository AY2122S1-CS2103T-W10-4/tp, pull requests merged in 2021-11, with the labels that each got.

#176 Bug fix
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: severity.Medium

#178 Disallow setting passing day as wedding date
  src/main/java/seedu/address/logic/commands/CountdownCommand.java
Labels: priority.High, type.Bug

#177 Make name matching to be case insensitive
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High, type.Bug

#175 Update User Guide based on the PED feedbacks
  docs/UserGuide.md
  docs/images/AddContact.png
  docs/images/Clear.png
  docs/images/DeleteIndex.png
  docs/images/UndoClear.png
  docs/images/UndoClear1.png
  docs/images/UndoClear2.png
  docs/images/UndoDelete1.png
  docs/images/UndoDelete2.png
  docs/images/UndoDeleteIndex.png
  docs/images/UndoGroup1.png
  docs/images/UndoGroup2.png
  docs/images/UndoGroupContacts.png
  docs/images/addPerson.png
  src/main/java/seedu/address/MainApp.java
Labels: priority.High, type.Chore

#194 Add tests for undo command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/UndoCommandParser.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/UndoCommandParserTest.java
Labels: priority.High, type.Chore

#185 Find and Shortcut commands test cases
  src/main/java/seedu/address/logic/commands/AddShortcutCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/RemoveShortcutCommand.java
  src/main/java/seedu/address/logic/commands/ShortcutCommand.java
  src/main/java/seedu/address/logic/parser/RemoveShortcutCommandParser.java
  src/main/java/seedu/address/logic/parser/ShortcutCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Shortcut.java
  src/main/java/seedu/address/model/person/predicates/PriceEqualsNumberPredicate.java
  src/main/java/seedu/address/model/person/predicates/PriceGreaterThanNumberPredicate.java
  src/main/java/seedu/address/model/person/predicates/PriceLessThanNumberPredicate.java
  src/test/data/JsonSerializableShortcutTest/typicalShortcut.json
  src/test/data/JsonShortcutStorageTest/notJsonFormatAddressBook.json
  src/test/java/seedu/address/logic/commands/AddShortcutCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListShortcutCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveShortcutCommandTest.java
  src/test/java/seedu/address/logic/commands/ShortcutCommandTest.java
  src/test/java/seedu/address/logic/parser/AddShortcutCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveShortcutCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ShortcutCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonSerializableShortcutTest.java
  src/test/java/seedu/address/storage/JsonShortcutStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Chore

#192 Update DarkTheme.css
  src/main/resources/view/DarkTheme.css
Labels: priority.High, type.Bug

#191 updated GUI result display at start up
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/Ui.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: priority.High, type.Bug

#190 Draft PPP
  docs/AboutUs.md
  docs/team/desmondto.md
  docs/team/johndoe.md
Labels: priority.Medium, type.Chore

#186 Finalize DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteByNameSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/PriceSum0.puml
  docs/diagrams/PriceSum1.puml
  docs/diagrams/PriceSum2.puml
  docs/diagrams/PriceSumSequenceDiagram.puml
  docs/diagrams/SetWeddingCountdown0.puml
  docs/diagrams/SetWeddingCountdown1.puml
  docs/diagrams/SetWeddingCountdownActivityDiagram.puml
  docs/diagrams/SetWeddingCountdownSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/CountdownGUI.png
  docs/images/CountdownResult.png
  docs/images/DeleteByNameSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/PriceSum0.png
  docs/images/PriceSum1.png
  docs/images/PriceSum2.png
  docs/images/PriceSumByTag.png
  docs/images/PriceSumSequenceDiagram.png
  docs/images/PriceTotalSum.png
  docs/images/SetWeddingCountdown0.png
  docs/images/SetWeddingCountdown1.png
  docs/images/SetWeddingCountdownActivityDiagram.png
  docs/images/SetWeddingCountdownSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/logic/commands/CountdownCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Chore

#187 Implement delete-by-name tests
  docs/images/AddPerson.png
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: priority.High, type.Chore

#189 Implement tests for price sum command
  src/main/java/seedu/address/logic/commands/PriceCommand.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/PriceCommandTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Chore

#193 Fix countdown corrupted json bug
  src/main/java/seedu/address/model/Countdown.java
  src/main/java/seedu/address/storage/JsonAdaptedDate.java
Labels: priority.Medium, type.Bug

#188 Implement tests for countdown command
  src/main/java/seedu/address/logic/commands/CountdownCommand.java
  src/test/java/seedu/address/logic/commands/AddShortcutCommandTest.java
  src/test/java/seedu/address/logic/commands/CountdownCommandTest.java
  src/test/java/seedu/address/testutil/TypicalDate.java
Labels: priority.High, type.Chore

#202 Update User Guide
  docs/UserGuide.md
  docs/images/AddPerson.png
  docs/images/GroupContacts.png
  docs/images/Report.png
  docs/images/UndoClear1.png
  docs/images/UndoClear2.png
  docs/images/UndoDelete1.png
  docs/images/UndoDelete2.png
  docs/images/UndoGroup1.png
  docs/images/UndoGroup2.png
  docs/images/deleteContact1.png
  docs/images/deleteContact2.png
  docs/images/findContact.png
Labels: priority.High, type.Chore

#203 add test to GroupCommand and its parser
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/test/java/seedu/address/logic/commands/GroupCommandTest.java
  src/test/java/seedu/address/logic/parser/GroupCommandParserTest.java
Labels: priority.High, type.Chore

#199 implement-test-for-tagInfo-command
  src/main/java/seedu/address/logic/commands/TagInfoCommand.java
  src/main/java/seedu/address/logic/parser/TagInfoCommandParser.java
  src/test/java/seedu/address/logic/commands/TagInfoCommandTest.java
  src/test/java/seedu/address/logic/parser/TagInfoCommandParserTest.java
Labels: priority.High, type.Chore

#215 Finalise PPP
  docs/AboutUs.md
  docs/team/Banana3021.md
Labels: priority.High, type.Chore

#213 Swap countdown setting past result to error message
  src/main/java/seedu/address/logic/commands/CountdownCommand.java
  src/test/java/seedu/address/logic/commands/CountdownCommandTest.java
Labels: priority.Medium, type.Bug

#209 Update Jar file link and version
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
Labels: priority.High, type.Chore

#207 Update ppp and DG UI diagram
  docs/images/UiClassDiagram.png
  docs/team/sj1999-bit.md
Labels: priority.High, type.Chore

#219 Add new images to UG
  docs/UserGuide.md
  docs/images/AddPerson.png
  docs/images/GroupContacts.png
  docs/images/Sample.png
  docs/images/Ui.png
  docs/images/UndoClear1.png
  docs/images/UndoClear2.png
  docs/images/UndoDelete1.png
  docs/images/UndoDelete2.png
  docs/images/UndoGroup1.png
  docs/images/UndoGroup2.png
  docs/images/deleteContact1.png
  docs/images/deleteContact2.png
  docs/images/findContact.png
Labels: priority.High, type.Chore
